config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'home#index'

  namespace :admin do
    root to: 'base#index'
  end

  scope :api do
    get :posts, to: 'api#posts'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  def index
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def posts
    mapped_posts = Post.all.map do |post|
      {
        id: post.id,
        title: post.title,
        sub_title: post.sub_title,
        text: post.body,
        category: post.category,
        photo: post.photo,
        publish_date: post.created_at
      }
    end

    render json: mapped_posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  # before_action :require_login

  private

  def post_params
    params.require(:post).permit(:author, :body, :title, :sub_title, :category, :photo)
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/base/index.html.slim
h1.text Admin page
= link_to 'Posts', posts_url

app/views/home/index.html.slim
h1 Home page of the application!
= link_to 'Admin page', admin_root_url

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title NewspaperServer Admin
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    / = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /
    title Newspaper
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :author
    = f.input :title
    = f.input :sub_title
    = f.input :category
    = f.input :photo
    = f.input :body

  .form-actions
    = f.button :submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table.table
  thead
    tr
      th Author
      th Title
      th Sub title
      th Category
      th Photo
      th Body Length
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.author
        td = post.title
        td = post.sub_title
        td = post.category
        td = post.photo
        td = post.body.length
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Author:
  = @post.author

p
  strong Title:
  = @post.title
p
  strong Sub-title:
  = @post.sub_title
p
  strong Category:
  = @post.category
p
  strong Photo link:
  = @post.photo
p
  strong Body:
  = @post.body


= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path